### ISSUE TITLE
Passing an existing Mongo Collection instead of creating a new Mongo.Collection

### ISSUE THREAD

**Issue by dgolds** [kahmali/meteor-restivus#10]
It took me a while to realize that I can't do..
```javascript
Lists = new Mongo.Collection('lists');
Restivus.addCollection('lists');
```
..since if I do this I get 
```
Error: A method named '/lists/insert' is already defined
    at packages/ddp/livedata_server.js:1444:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object]._.extend.methods (packages/ddp/livedata_server.js:1442:1)
    at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:886:1)
    at new Mongo.Collection (packages/mongo/collection.js:208:1)
    at Restivus.Restivus.addCollection (packages/nimble:restivus/lib/restivus.coffee:74:50)
    at repl:1:10
    at /Users/davidgolds/Desktop/kip/kipGameDB/.meteor/local/build/programs/server/shell.js:169:23
```

..So how can I have an API on a collection that I also want to manipulate elsewhere in my Meteor code!?

**Comment by kahmali** [comment]
Wow. This is what happens when you create bad test cases. Shame on me. That would certainly be unacceptable! I misunderstood the Mongo.Collection constructor. I'll need to change the API since `new Mongo.Collection()` can only be called once for each collection. Meteor expects you to store these as global variables, so I'll just fix it so the collection is passed into `Restivus.addCollection()`, instead of the name of the collection. I was trying to be fancy and use the name of collection as the URL path when creating the route, which fits with RESTful conventions, but I'll have to require the user to pass a path in Restivus.add() as well (I would try to use the variable name by default if javascript had reflection that supported that). This will be API-breaking, but I wouldn't call the API functional as it is, so I'll put this in a bump to version 0.6.1. I'll keep you posted. I'll need to update the docs as well, but I should be able to get this all fixed and pushed up in the next 24-48 hours. I'm sorry about this terrible mistake! I'll have the fix up asap! 

Just to explain my rather stupid mistake: at some point I changed the capitalization of the collection name I was testing, which created a new collection. I didn't update my tests, so by the time I got around to testing adding a route on an existing collection, I was testing against an old collection that didn't have any call to `new Mongo.Collection()` anywhere else, so it never produced this error. Stupid, I know. Once I clean up any bugs associated with this latest update my plan is to implement some extensive automated testing. It's long overdue.

**Comment by dgolds** [comment]
Ok. Glad I wasn't misunderstanding this. If you look at CollectionAPI you'll see how they permit the collection to be passed in. Please let me know when you might have this fixed.. I'd like to use Restivus if I can, but at present only CollectionAPI works for me.

**Comment by kahmali** [comment]
Yeah, I definitely used Collection API for inspiration. I thought I was doing the user a favor by not having to make them create the collection locally or be required to pass a path name when it will typically match the collection name, but I misunderstood the `Mongo.Collection` constructor. I'm really sorry if this caused you any trouble. Automated testing should help me avoid issues like this in the future. I'll keep you posted on the update.  I'm working on it now!

**Comment by kahmali** [comment]
It wasn't as bad as I expected. As with the Collection API, the user is now required to pass the collection as the first parameter in `Restivus.addCollection()`. Luckily, I was able to access the name of the collection through the `Mongo.Collection` object, so I use that name as the default path now. It can still be overridden using the `path` in the 2nd parameter passed to `Restivus.addCollection()`.

Please [update to v0.6.1](https://github.com/kahmali/meteor-restivus#upgrading-from-060) and let me know if you have any other issues converting over from Collection API. I have to get some sleep now, but I'll check back later. Thank you so much for reporting this issue!

**Comment by dgolds** [comment]
Thanks. I will try it soon. I appreciate the rapid turnaround. Now I just
need to find a good forms library that will take the pain out of making an
edit ui

**Comment by kahmali** [comment]
I believe what you're looking for is [`aldeed:autoform`](https://github.com/aldeed/meteor-autoform). Great package. Check it out.

**Comment by dgolds** [comment]
0.6.1 is working great for me - thx!

**Comment by kahmali** [comment]
Awesome! I'm going to go ahead and close this. Let me know if you have any other issues. Thanks again for reporting this bug!
