### ISSUE TITLE
Authentication (authRequired:true) via HTTP(S) GET with queryParams

### ISSUE THREAD

**Issue by andrewash** [kahmali/meteor-restivus#154]
Greetings,
Thank you so much for putting Restivus together, for, you know, the rest of us.
It's been a delight to use.

I have a REST API with a large number of MP3 recordings of private messages by my app's users. For privacy reasons, I don't want to make them accessible for HTTP GET downloading without authentication.

I'd like to include an <audio src={URL}> element in a page that points to the URL of a recording, and includes as queryParams the X-User-Id and X-Auth-Token.

Is this possible?
Is there a better way you'd recommend I solve this problem?

I've thought about transmitting the files via Meteor's pub/sub DDP layer, but this article made me doubt the wisdom of that approach (https://kadira.io/academy/meteor-performance-101/content/reducing-pubsub-data-usage)

Be well,
Andrew

**Comment by steedos** [comment]
It's not secure because http urls can be logged even use https

**Comment by andrewash** [comment]
Oh, of course, I had forgotten about that. Ok, I'll go back to the drawing board on this one. Thanks for the help

**Comment by kahmali** [comment]
As long as the endpoint is authenticated, the request is transmitted over **https** (you just need to setup SSL on the server hosting these files), and you trust the client (i.e., they have provided a valid userId and auth token), then this is secure. I think @steedos was just warning you that _nothing_ is secure when transmitted over http, because anyone that intercepts the transmission will be able to access the unencrypted request/response. 

Also, thanks for the compliment and sorry for the delayed response. I just launched a Meteor app into production and it's been owning all of my time. Maybe I'll have a bit more time to spare for Restivus in the near future. That's my hope at least.

**Comment by andrewash** [comment]
You're welcome @kahmali :-)
I think what @steedos was pointing out is that if I include the credentials in the HTTP GET URL, then they'll be transmitted unencrypted, because URLs aren't encrypted, only the payload. I'll close the issue for now and consider alternatives.
