### ISSUE TITLE
WADL-to-REST generator?

### ISSUE THREAD

**Issue by hujhax** [kahmali/meteor-restivus#21]
One way to describe a RESTful interface is via [WADL](http://en.wikipedia.org/wiki/Web_Application_Description_Language), the Web Application Description Language.  There are lots of Java tools that convert WADL to REST, but nothing for meteor (and almost nothing for JavaScript, in fact).

Could this be an option for RESTivus?  Or perhaps a package built on top of RESTivus?

**Comment by kahmali** [comment]
This is actually the first I've come across WADL. Very interesting stuff. I love the idea of allowing an existing specification of a REST API to just plug into Restivus. Restivus can certainly handle (or be updated to handle) anything that the WADL spec requires. 

I would definitely build this as a separate package that was capable of interpreting the WADL REST definition, and just use Restivus for the API construction. I think Restivus would feel bloated if it included it, as it's definitely not fundamental to REST API development. I'd rather keep Restivus as a "core" package and build any features like this as separate add-on packages. At some point I will probably break out the support for collections into a separate package, where it belongs. 

That being said, there are still some core features that need to be supported before I can add something like this myself (e.g., API versioning, JSON PATCH support, endpoint hooks). However, if you or anyone else would like to build this as a separate package I would not only encourage it, but also assist however I can, especially where Restivus is concerned.

**Comment by hujhax** [comment]
Cool!  Rishat, if you decide to try making this, let me know so I can help too.

**Comment by kahmali** [comment]
This issue was discussed in the comments section in @hujhax's great write up on Meteor. Just want to add the information here before closing the issue for now. 

**Rishat Muhametshin:**
_"I mainly work on enterprise software, and the projects often involve several teams (incl. third-parties) and dozens participants. Since almost everything is being built around SOA approach, there are plenty of REST APIs. To simplify the development process, we've come up with the convention that the development of every service is preceded by a data contract; and WADL is one of the easiest (yet standardized) ways to create it._

_Most services are being built using Java, and most of the time this path is simply more expensive than getting these services up and running in a light and versatile environment which Node provides. Moreover, API consumer apps don't care what technology the API has been built with, but time is usually limited and some kind of mock API is often critical, as soon as possible._

_This being said, a simple CLI tool to deploy REST API from WADL would save a lot of time and resources for me and maybe three other guys around the world who have faced the same problem. I'm not quite sure this problem is widespread or has any significant audience."_

And my response:

Thanks for the detailed response Rishat! This could definitely be built in Meteor on top of Restivus, but as you've noted here it's a bit too obscure a feature for me to devote any time to it. If you do plan to develop this tool in Meteor please contact me if you need any advice or assistance in using Restivus to build it. I'm happy to help wherever I can. I'm going to close the Issue Peter opened on GitHub for now, but if you or anyone else ever decide to pursue this project I'll be happy to reopen it and join the discussion. Thanks again for the information on WADL!
