### ISSUE TITLE
Custom authentication

### ISSUE THREAD

**Issue by cameronb23** [kahmali/meteor-restivus#213]
My custom authentication method doesn't seem to be working. The way I'm authenticating is whenever a request is made it checks the headers, and tries to find a Server document that matches those credentials. If it finds one, it returns the system user, and the request should be authenticated. Everything works, except it keeps saying you must be logged in to do this even when a server is found and a user is returned.

https://dpaste.de/maVy

**Comment by kahmali** [comment]
Everything there looks good, except instead of just returning the user, you should return an object of the form 
```js
return {
  user: user
}
```

I [updated the code snippet you posted](https://dpaste.de/LWs8#L38) to reflect that. Sorry about the [lack of documentation for custom auth](https://github.com/kahmali/meteor-restivus/issues/98). The best explanation I've ever given can be found [here](https://github.com/kahmali/meteor-restivus/issues/129#issuecomment-133120800), although it goes into a lot of extra detail that needs to be stripped away.

Let me know if returning that object works for you. Also, since you return the fully authenticated user, you don't need to provide the path to the token in the [`auth.token` config option](https://dpaste.de/LWs8#L4) (no problem if you do, but it'll be ignored). If that doesn't fix your issue just say the word and we'll get to the bottom of it.

**Comment by cameronb23** [comment]
Works perfectly now thanks :+1:

**Comment by kahmali** [comment]
Awesome!
