### ISSUE TITLE
After logging in, it does not set the user in session i.e. Meteor.user() is null

### ISSUE THREAD

**Issue by prashantgaikwad** [kahmali/meteor-restivus#222]
I am making a Meteor.call in action function of my API definition like this
  post: {
     authRequired: true,
     action: function addItem() {
        Meteor.call('Item.add', this.bodyParams);
    }
}
 Inside the meteor call I have checks for authentication and authorization for which I need user from Meteor.user() which I am getting as null.
Please help.
Prashant

**Comment by kahmali** [comment]
Restivus is a server-only REST API package. If you want to log into a meteor client, you can use one of the available packages (e.g., `accounts-password`). Otherwise, you're responsible for storing the auth token on any client that authenticates via your REST API, and using that token to make subsequent REST calls.

**Comment by prashantgaikwad** [comment]
I figured out a way to work without using Meteor.user().
Thanks man.
It's a great package.
