### ISSUE TITLE
Option to allow custom request headers

### ISSUE THREAD

**Issue by Twisterking** [kahmali/meteor-restivus#236]
So there was an [issue](https://github.com/kahmali/meteor-restivus/issues/151) but it was closed again almost immediately ...
Could we have an option to allow custom headers for a request? Afaik, at the moment only the two "X-..." auth headers are allowed. I would like to use some custom ones.
Thanks in advance!

**Comment by kahmali** [comment]
Hi @Twisterking. Great news! You can already accept any headers you want 😃  They're available in any endpoint as `this.request.headers["<Custom Header>"]`. Here's an [example](https://github.com/kahmali/meteor-restivus#javascript-1) of me accessing the custom auth headers (in the `auth.user` function). I'm going to close this since I'm fairly certain that will resolve this issue for you. Let me know if I'm mistaken.
