### ISSUE TITLE
Method POST Not received bodyParams from client with fetch 

### ISSUE THREAD

**Issue by tanmynguyen** [kahmali/meteor-restivus#269]
Hi guys .
I can't received bodyParams from client.
*config api server:
<img width="667" alt="screen shot 2017-04-13 at 16 25 09" src="https://cloud.githubusercontent.com/assets/11315567/24998882/cef37252-2065-11e7-9c53-4431d1ba90a5.png">
*client call api:
- head
<img width="945" alt="screen shot 2017-04-13 at 16 26 03" src="https://cloud.githubusercontent.com/assets/11315567/24998966/073e0a50-2066-11e7-9ca2-599a1b18f540.png">
- body
<img width="507" alt="screen shot 2017-04-13 at 16 27 34" src="https://cloud.githubusercontent.com/assets/11315567/24999033/2f09ee0a-2066-11e7-9911-870305c96f80.png">
* And log from server:
<img width="278" alt="screen shot 2017-04-13 at 16 28 35" src="https://cloud.githubusercontent.com/assets/11315567/24999045/438fcc32-2066-11e7-8e0f-31921cf0cd2b.png">

Who can't help me. Please!
But I when use api /login worked!!!

**Comment by ghost** [comment]
Experiencing exactly the same behavior with 0.8.11.
The weirdest thing is that everything worked until some point and no code/packages updates precede this issue.

**Comment by tanmynguyen** [comment]
@Rvach  Thanks you. Fixed

**Comment by ghost** [comment]
But does update to 0.8.12 resolved issue for you?
I cannot update due to dependencies constraints accounts-passwords to 1.1.13 while restivus requres 1.3.*.
I've tried to use restivus as local package with accounts-passwords set to 1.1.3 (as bcrypt issue seems fixed there, though I'm not sure) and it seems to work fine with it, even login credentials hashing works fine. Nevertheless the issue stays, at some point POST endpoint retreives empty body.

**Comment by cbruce11** [comment]
I'm still having this issue, did you find a fix?

**Comment by shyal** [comment]
i can't post restful data with restivus either.... man meteor is turning into such a joke.
