### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by awrelll** [kahmali/meteor-restivus#36]
Hello,
I get this error when i try to start my app 

Not migrating, already at version 5
Restivus configured at api/ without authentication
{"line":"52","file":"synced-cron-server.js","message":"SyncedCron: scheduled \"Randomize Profile Random Sorter\" next run @Wed Apr 22 2015 14:32:58 GMT+0000 (UTC)","time":{"$date":1429713178307},"level":"info"}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)

Can you please guide me ?
Thanks!

**Comment by kahmali** [comment]
I'll need a lot more information to help. Can you try to reproduce the error and give me the steps? Even better would be a minimalist test repo that produces the error. Unless all you're doing is adding Restivus to an empty project and it's throwing that error, I need to know as much about the rest of your project configuration as possible. That's why it's best to try to reproduce these errors in an empty project. There's a chance this has nothing to do with Restivus (not that I won't gladly accept responsibility if it is). I'll be glad to help either way, but I just need as much information as you can spare. As it is, I don't see anything in that stack trace that would lead me to believe that Restivus was at fault there.

**Comment by awrelll** [comment]
I cloned the we work meteor repo https://github.com/nate-strauser/wework and started the app, that's all. I'm on Ubuntu 14.04 x64

**Comment by kahmali** [comment]
And what leads you to believe it's Restivus that's causing the issue? Have you opened an issue in that repo? Can you link me to it?

**Comment by kahmali** [comment]
In that stack trace it looks like Restivus initialized without any issue.

**Comment by awrelll** [comment]
ok, sorry, my bad, i'll look it up in detail!
Thanks for your time!

**Comment by kahmali** [comment]
No problem! If it turns out to be linked to Restivus please don't hesitate to reopen this issue. Good luck!
