### ISSUE TITLE
How to remove CORS?

### ISSUE THREAD

**Issue by radiegtya** [kahmali/meteor-restivus#39]
I have tried many ways to remove CORS but still failed.

"No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin "

I have tried this
```
Restivus.addRoute('cmsUsers', {authRequired: false}, {
    post: {
        authRequired: false,
        action: function() {
            this.response.setHeader('Access-Control-Allow-Origin', '*'); //ADDING THIS LINE

            var doc = this.bodyParams;
            if (Accounts.createUser(doc)) {
                return {
                    headers: {
                        'Content-Type': 'text/json',
                        'Access-Control-Allow-Origin': '*'
                    },
                    body: {status: 'success'}
                };
            }
            return {
                headers: {
                    'Content-Type': 'text/json',
                    'Access-Control-Allow-Origin': '*'
                },
                statusCode: 500,
                body: {status: 'fail', message: 'Internal Server Error'}
            };
        },
    },
});
```

but still no luck for me. Please help, thanks

**Comment by kahmali** [comment]
In the example you gave, you're doing exactly what you should do to _add_ CORS support. By providing the wildcard option `*` to the `Access-Control-Allow-Origin` header, you're configuring the endpoint to accept requests from _any_ origin (domain). To remove CORS, you would need to specify that you only accept requests from your own domain. So return something like this instead: 

```javascript
            return {
                headers: {
                    'Content-Type': 'text/json',
                    'Access-Control-Allow-Origin': 'https://yourwebsite.com'
                },
                statusCode: 500,
                body: {status: 'fail', message: 'Internal Server Error'}
            };
```

What I will do is provide an API configuration option so you can automatically default to CORS being off, and then I can also allow users to simply set a config option on an endpoint (`enableCors: true`) to toggle it on a per endpoint basis. That will DRY up the code, instead of having users manually set the CORS headers in each endpoint. Let me know if this temporary fix causes any issues when testing in localhost. I'm not 100% sure if localhost get's a free pass in CORS. I'll keep this issue open until I add the config option on the API and endpoints (and routes, too, of course). I'll post any progress on that in here. 

Here's some pretty comprehensive [documentation of CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).

**Comment by kahmali** [comment]
As of v0.6.5, you can now disable CORS on all endpoints by default using the [`enableCors` configuration option](https://github.com/kahmali/meteor-restivus#enablecors). This should resolve this issue and help you DRY up your code (since you can disable on all endpoints at once instead of having to do it on each). Let me know if you have any issues with this or anything else.

**Comment by radiegtya** [comment]
wow, thanks @kahmali
