### ISSUE TITLE
TypeError: Cannot read property '_name' of undefined

### ISSUE THREAD

**Issue by wesyah234** [kahmali/meteor-restivus#59]
I tried installing this per the readme, and then put the "quick start" javascript in my javascript file, and I get the following error on the server:

W20150506-11:44:08.203(-5)? (STDERR) /Users/x/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150506-11:44:08.203(-5)? (STDERR) 						throw(ex);
W20150506-11:44:08.203(-5)? (STDERR) 						      ^
W20150506-11:44:08.227(-5)? (STDERR) TypeError: Cannot read property '_name' of undefined
W20150506-11:44:08.227(-5)? (STDERR)     at Restivus.Restivus.addCollection (packages/nimble:restivus/lib/restivus.coffee:96:38)
W20150506-11:44:08.227(-5)? (STDERR)     at app/restivus.js:17:12
W20150506-11:44:08.227(-5)? (STDERR)     at app/restivus.js:72:3
W20150506-11:44:08.227(-5)? (STDERR)     at /Users/x/NetBeansProjects/restivusDemo/.meteor/local/build/programs/server/boot.js:222:10
W20150506-11:44:08.227(-5)? (STDERR)     at Array.forEach (native)
W20150506-11:44:08.227(-5)? (STDERR)     at Function._.each._.forEach (/Users/x/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150506-11:44:08.227(-5)? (STDERR)     at /Users/x/NetBeansProjects/restivusDemo/.meteor/local/build/programs/server/boot.js:117:5

**Comment by kahmali** [comment]
Hi there! Thanks for reporting this issue! I did notice a small omission in the quick start example, but it doesn't appear to be the cause of this issue. The error you're getting is caused by passing a null or undefined object as the first parameter to `Restivus.addCollection()`, which would only happen in the quick start example if you didn't copy in the first line that initializes the collection. Can I see a complete copy of your code? 

The omission I detected was that the `Posts` collection I use in the custom route is never initialized in the example. I'm surprised nobody has yelled at me for that. 

I'll go ahead and fix that omission in the Quick Start example, and also handle that error better so that it's clear what's happening there.

**Comment by wesyah234** [comment]
oh... ok, I see it's passing Meteor.users... that must be what is undefined in my test project... do I need a certain package for this to be defined properly?  or do I need to be doing authentication / login?

**Comment by kahmali** [comment]
I'm sorry about that. Sometimes I forget that the accounts package is not part of core. I'll add a note for that into the quick start example (or more likely, just use another custom collection instead). 

You are correct, though. You would need `accounts-password` or any of the other `accounts` packages to access the `Meteor.users` collection.

**Comment by wesyah234** [comment]
No worries!... I put together a very bare bones example at https://github.com/wesyah234/restivusDemo which doesn't use the accounts packages... let me know if you have any feedback.  Other than this small issue, your package has been very easy to get started with.
