### ISSUE TITLE
Alternative Auth Token behavior

### ISSUE THREAD

**Issue by Tolmark12** [kahmali/meteor-restivus#6]
Question, we have an API where we generate an auth token for the user (accessible in their dashboard). They then pass that token as proof of authentication when making API calls. It would be cool if one could configure restivus to use alternative auth method; instead of the tokens generated via the `login` endpoint.

I'm just thinking out loud here, but does that spark any thoughts?

**Comment by jasonxeno** [comment]
+1

Using X-User-Id and X-Auth-Token in the header seems a bit convoluted in this day and age, and I would much rather have users use the rest API by passing a single 'api_key' field in with the post data to authenticate.

**Comment by kahmali** [comment]
First off, let me just say that the security on Restivus is weak at best right now. I certainly plan to add base64 decoding of passwords at the very least, so they can stop being sent plain text. I also need to conform to the standard for basic auth. 

I'm trying to figure out if both of you are actually having the same issue. 

@Tolmark12 Are the auth tokens that you generate for the user stored in the Meteor.users collection? Are these auth tokens unique to each user? If both of your answers are yes, it would be very easy for me to allow you to configure the API to look for the auth token in a different location within the user document during authentication. Are you okay authenticating via the header as it is, or is that also a problem for you?

@jasonxeno I think your issue is not with the auth token, but rather you are looking for a completely different style of authentication. When you say "a single api key," do you mean an api key that will not be unique to each user? Is your issue with using headers, using those specific headers, requiring a user ID, requiring a user-specific auth token, or all of the above?

**Comment by jasonxeno** [comment]
@kahmali thanks for asking for clarification!

The security issue can be solved by just forcing SSL use on the meteor app if someone wants more security. Then there is no plain text. That is what I am doing for my production app.

So if I have a user coding for my rest API, I want them to be able to do it fast and in the least code possible. It seems redundant to have to log in to an api, and also put things in the header. If an app  is using HTTPS anyway, what benefit does the X-Auth in the header provide?

Ah, I see, the benefit is that it would let you secure a GET api. But my api is just going to use POST and parse POST data. So I would prefer just to add an API key, generated from the GUI by the user and attached to the user, to one of the POST data fields for ex. api_key. Then that user can use the api as that user if the just have the key. For added measure, there could also be a required username field with the normal meteor username In addition to api_key.

Does that make sense?

Thanks for your work on Restivus!

**Comment by jasonxeno** [comment]
I reread your docs again and it looks like I don't actually have to use headers for auth, I can put auth in in post data just like in reststop2 without any headers. I just got a bit confused when I read this before because right above the post data Auth example it talks about headers. Then it shows the  nonheaders example, and then the headers example.

With that said, I want to generate an api key (or api token) in the meteor GUI while logged in as a user. I click generate. It then appears, 'here is you API key.' This can be stored in the user object. Then I want to use that API key for the authKey in the restapi. I don't want a new username generated, just use the username from normal Meteor. I don't want to have a user login through the API and generate a login token that can change. I just want the user to use the API key they generated in the GUI, and it never expires automatically, and can be seen again from the GUI again optionally.

**Comment by kahmali** [comment]
In response to part 1 of your second comment (I'll address everything else soon, I promise), that's actually not available in Restivus, although I could change that. I missed it when I converted over the RestStop2 docs. Sorry about that. That's an API-breaking change, as it will collide with any Restivus users that may already be using a "user" or, less likely, "authToken" in any POST data. That's one of the reasons I really prefer to keep it out of the body and in the header. It's makes for a much cleaner API, without any worry about collisions. I'll need to do some research into authenticating via the body like that, and the best practices around it. I could make the keys for it more unique, at the very least (e.g., "xUserId" and "xAuthToken", or something like that). What platform are you consuming the API from? Is it that much of a hassle to put the auth data in the header? From my earlier research, that seemed like a preferred method. I'll have to look into again, as I said.

**Comment by jasonxeno** [comment]
Ah, that explains why I couldn't get that to work. Basically I have users using reststop2 that send no headers and are sending just POST data and I am looking to upgrade to restivus.

About consuming the API, honestly the headers thing is easy to someone like you or I. So my question might seem strange. But some of the users who are now using my current API and would use an API have never connected to an API before in their life. They don't even know what a header is. I'm not in the business of teaching, I just want them to be able to get an API up to my system as fast and possible with the least amount of code possible efficiency.

as for

**Comment by jasonxeno** [comment]
As for breaking compatibily, putting the auth in the body could be an option just like useAuth. For example, useAuthBody, then backwards compatibility is maintained.

I would rather not use X in front of things as that is confusing for api consumers but I can always fork and change the field names if you are worried about collisions.

My goal is essentially making the consuming API code whereever it is consumed, could be any language, as small as possible in case the coder doesn't know about things like HTTP protocol and headers and all that jazz. I'm willing to make my code more convoluted in my end, which users will never see, to make it happen.

Thanks for the response and question!

**Comment by kahmali** [comment]
_I want to generate an api key (or api token) in the meteor GUI while logged in as a user. I click generate. It then appears, 'here is you API key.' This can be stored in the user object. Then I want to use that API key for the authKey in the restapi. I don't want a new username generated, just use the username from normal Meteor. I don't want to have a user login through the API and generate a login token that can change. I just want the user to use the API key they generated in the GUI, and it never expires automatically, and can be seen again from the GUI again optionally._

It sounds like this could be achieved with the same solution I suggested for @Tolmark12 above. You could be responsible for generating and storing an auth token somewhere in the Meteor.user document. You can do whatever you want with the token, including displaying it to the user and managing it's lifetime. I can allow you to configure where this auth token should be found in the User document, and I can check against it during authentication (e.g., `customAuthToken: "auth.apiKey"`). This would check for the auth token in the `Meteor.user.auth.apiKey` field and authenticate against that. I could even allow you to define this as a function that returns an auth token as well (I would accept both forms). The only thing I don't like about Restivus right now is that it requires `useAuth` to be true for authentication to be checked, which means you get some unnecessary endpoints generated if you don't intend the user to login via the API. I will change this in the future so that having the default login and logout endpoints does not affect your ability to authenticate. 

_So if I have a user coding for my rest API, I want them to be able to do it fast and in the least code possible. It seems redundant to have to log in to an api, and also put things in the header. If an app is using HTTPS anyway, what benefit does the X-Auth in the header provide?_

So, just to make it clear (and I think you realize this from your very next statement)), the benefit of putting the auth in the header as opposed to the body is that:
1. It allows authentication in GET requests, which is a typical use case
2. It's just cleaner, since it separates the auth data from the actual POST or PUT data, which typically makes parsing that data easier and more efficient. 

_As for breaking compatibility, putting the auth in the body could be an option just like useAuth. For example, useAuthBody, then backwards compatibility is maintained._

This would certainly be an option. The only thing about this is that if a user configures authentication via the request body, then authenticated GET requests will not be possible, which seems limiting and somewhat confusing to me. 

_I would rather not use X in front of things as that is confusing for api consumers but I can always fork and change the field names if you are worried about collisions._

I agree, that's terrible. I'll avoid something like that at all costs.

_My goal is essentially making the consuming API code wherever it is consumed, could be any language, as small as possible in case the coder doesn't know about things like HTTP protocol and headers and all that jazz. I'm willing to make my code more convoluted in my end, which users will never see, to make it happen._

I completely understand you wanting to make your API as simple as possible, and I'm also willing to do anything more difficult on my end to make it easier on the Restivus users. I just don't want to promote any bad practices in Restivus. I'm not saying this is definitely a bad practice, I just can't find any resources saying it's good practice. It seems pretty standard to pass auth data via headers. I'm trying to wrap my mind around someone consuming a REST API without understanding the absolute basics of HTTP, which to me would include headers. Your users are developers, right? I've never used a platform that didn't make adding headers trivial. I'm not shutting this down, I just need more convincing here. My thought here is that a developer shouldn't be consuming a REST API without understanding headers. It's a web standard and any self-respecting developer should take the 15 minutes to learn of their existence. Are there really folks out there doing something as advanced as consuming a REST API without understanding the concept of a basic key-value store? Also, aren't most clients going to have to set the Content-Type header on their end, making it almost a necessity that someone consuming the API would need knowledge of headers? Again, this could be a false assumption on my part.

**Comment by jasonxeno** [comment]
Thank you for the in depth response! I agree with your suggestions and you are indeed understanding my needs correctly. You have very well thought out communication analysis skills by the way, so I'm impressed!

My app connects to over 20 APIs of various types made in various frameworks, different versions of XMl, SOAP, REST, custom, seemingly randomly made up, some are flabergastingly convulted. They litterally take 10x as much code to connect to than they should. So part of the reason someone would use my app is that it takes the minimum number of steps to do what you need.

I could be in the minority with my needs, but I would definitely appreciate any help via restivus, I don't want to reinvent the wheel if there is a common goal.

If we really analyze REST and the HTTPS protocol, it was made long ago and even though it is good practice to use all the commands and headers, POST is the most powerful out of the commands and can do anything the others can, because the data sent is not limited like GET and has to be formed into the URL itself, and an indicator for PUT etc, can just be put in the post fields, and these basic CRUD commands don't compare to the variety of commands that a modern database has like mongo has available that you may want to do via API.

I completely understand trying to wrap your head around a developer who would have a hard time with headers. Think of it this way. 50% of coders are below average by definition. And then another 50% of those coders are below average of the below average coders. So we got 25% of these coders around making decisions running the IT of companies that would integrate with my API. They are probably more likely to want to connect to my API because it's easier than normal.

Here is another example, I have a client, a company with $15 million revenue. The head of IT  coded their order processing system that runs in 30 stores successfully. The company wanted to buy my app cloud service, also wanted to integrate some data from their system. The head of IT never heard of JSON or REST before. So I had convince them it was easy and I had to train him how to connect to my reststop2 api in their dotNET stuff, parse JSON, explain the HTTP protocol, find out how to connect externally with dotNET, etc. It is something they never ran into before.

Sure I can turn down these types of clients, but if they were better or smarter they would have already solved their tech needs themselves without me.

So it comes down to making the least amount of intructions to connect to my API, and the things I mentioned help with that.

From the perspective of the package developer it makes sense to look out for good practices. From my perspective as a user, if those good practices are adding extra steps that I see a way to eliminate, I question the good practices for myself, but recognize they may help others with different needs, and I may end up wrong for unkniwn reasons so it helps to put my ideas out there to get feedback.

Thank you for your time!

**Comment by kahmali** [comment]
OK, you make a very solid case for keeping your API simpler than normal. I think I have a solution that will keep Restivus from leading users into bad practices while still allowing the flexibility that you'll need to  authenticate via the request body. What if I allow you to configure an `authenticate` function that will override the default authentication? From this function, which would have the normal endpoint context minus the `user` and `userId`, I could either require that you return an object like `{userId: "abc123", "authToken": "def456"}`, which I would validate against the user's configured `customAuthToken` field (or against Meteor's default login token by default), or I could require you to return the authenticated user (or `undefined` or `false` if auth fails). I'll think about that some more, but if you have any input on that I'd be glad to hear it. I could of course try to implement both levels as well, so I'll try to think of a clean way to do that if possible. I think worst case scenario I'll expose the more flexible method, which would be having you return an authenticated user. No matter what, I'll still wrap it up so Restivus can do some of the work, like attaching the user and their ID to the endpoint context. 

Let me know if that's a clean enough solution for you, or if you have any questions about it. I would be happy to write up an example for the docs that shows how to define a custom auth function that uses the RestStop2-style request body authentication instead of the default headers.

**Comment by kahmali** [comment]
Oh, and regarding your stance on POSTs, I think they can be misused at times. I try my very best to conform to REST standards for the HTTP methods, so I'm a firm believer in POSTs only being used to create new resources, GETs being used to read resources, PUTs only being used to update entire resources, and PATCHes being used for updating partial resources. So I would disagree with you when you say, "these basic CRUD commands don't compare to the variety of commands that a modern database has like mongo has available that you may want to do via API." I think a lot of people are overlooking the [PATCH method](http://jsonpatch.com/), which is knocking on the door of RFC standardization, and is supported on the majority of modern platforms. I would say PATCH is the "most powerful" of all the HTTP methods. With PATCH, you get all major updates on your collections, and using query params in GETs will allow you to do advanced queries on collections. I think there are ways to conform to REST standards that are actually ideal for Mongo and other modern databases. I'm trying my best to support these in Restivus, including some very cool PATCH support on Meteor Collections coming soon, hopefully. The next big update for Restivus (coming any day now), will pave the way for that.

**Comment by jasonxeno** [comment]
That is definitely a clean enough solution, and the requirement of my responsibily of returning the authenticated user sounds like the best plan for adding auth flexibility of restivus. It's much appreciated.

Reading your JSON PATCH link definitely shows that the PATCH is the most powerful. I see now that my stance with just using POST was biased towards my specific needs for simple instructions, and my specific use case where users would not have access to perform PATCH related tasks. With restivus being a full featured REST API framework using the full array of commands as they are intended should definitely be the forefront of the project as you are working on.

I think that POST is overused because a larger percentage of systems don't want or need users to have much access to PATCH type of commands. But when users need more access or two systems of more equal/advanced access to each other need to communicate, I see the role that using the wide spectrum of HTTP commands fills. I look forward to what you come up with adding direct Meteor support for these!

**Comment by Tolmark12** [comment]
@kahmali: 
__Are the auth tokens that you generate for the user stored in the Meteor.users collection? Are these auth tokens unique to each user?__

Yes.

__Are you okay authenticating via the header as it is, or is that also a problem for you?__

We're using header, wouldn't hurt to also allow optional authentication via query parameters, but not critical

__I could even allow you to define this as a function that returns an auth token as well (I would accept both forms).__

Yeah, that sounds perfect. We generate an API token for our users and in our docs instruct them to submit all API requests with the API token concatenated with their username as an additional small layer of security (eg: `username.ADNI453N3ANS0`)

Thanks again for the great work and being so responsive (!) If you want any help implementing this, let me know.

**Comment by kahmali** [comment]
Update to the latest version, [v0.5.8](https://github.com/kahmali/meteor-restivus/blob/master/CHANGELOG.md#v058---2015-02-11), and check out the [Configuration Options](https://github.com/kahmali/meteor-restivus#configuration-options) in the docs for more details on how to configure custom authentication. Let me know if this solves the issue for you.

**Comment by jasonxeno** [comment]
Looking good, I look forward to testing this out! Thank you.

**Comment by Tolmark12** [comment]
Thanks @kahmali! Bout to test / implement it now.

**Comment by Tolmark12** [comment]
@kahmali Working great so far, thanks again! :clap:

**Comment by kahmali** [comment]
I'm going to go ahead and close this issue. @jasonxeno If you run into any problems once you've had a chance to test I will reopen it. Thanks to both you and @Tolmark12 for the great discussion around this issue!
