### ISSUE TITLE
User created with Meteor.createUser() not found by Restivus authentication call

### ISSUE THREAD

**Issue by sspann** [kahmali/meteor-restivus#71]
Hi, 

We are creating a user with `Meteor.createUser()` and attempting to authenticate with the Restivus `/login` route but Restivus is returning `"message": "User not found"`. The user can be seen with `Meteor.users.find().fetch()` and has a `username` property:

`[Object_id: "6vw27T9NFwL3pG9ef"username: "myusername"__proto__: Object]`

Can you think of a reason why Restivus is not finding the user?

Many thanks!

**Comment by kahmali** [comment]
There is no known issue that would cause this. Have you tried reproducing the error? If so, can you provide me with the steps to reproduce, or a test repo if possible? If you can't reproduce it, can I see the request body? You can and should remove any actual password you're using.

**Comment by sspann** [comment]
Thank you for the quick response. We're just testing locally with the sample curl command in the docs: `curl http://localhost:3000/api/login/ -d "password=mypassword&user=myusername"`

We added `useAuth: true` to `Restivus.configure` and we can view the user on server side 
```json
{ _id: '6vw27T9NFwL3pG9ef',
createdAt: Fri May 15 2015 14:03:24 GMT-0500 (CDT),
services: { password: { bcrypt: '...' } },
username: 'email@email.com' }
```

**Comment by kahmali** [comment]
I think I see the problem. It looks like you're using an email address in the username field. Is there a reason that this is necessary? Why can't you store the email in the user's email field? I kept the RestStop API when I converted over, which used a single `user` field for login and interpreted any value with an `@` symbol within it as an email. So it's expecting that value in the `emails.address` field of the `Meteor.user` document. I'll consider extending the API so that you can specify a `username` or `email` when logging in, instead of the generic `user`.

**Comment by sspann** [comment]
I believe this solved my problem. Thank you for you help!!

Steven

**Comment by kahmali** [comment]
Awesome! No problem! Thanks for reporting the issue!
