### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by dandv** [kahmali/meteor-restivus#75]
(a great OCD task ;)

I'm back, and was hoping to see at https://github.com/kahmali/meteor-restivus/releases the notes about iron-router being replaced with simple:json-routes.

**Comment by kahmali** [comment]
The reason the release notes aren't there is because the update still hasn't been released. Instead of doing a bunch of small API-breaking changes one-by-one, I just decided to lump a bunch of them into the [v0.7.0](https://github.com/kahmali/meteor-restivus/tree/0.7.0) release, which is [still pending](https://github.com/kahmali/meteor-restivus/milestones/v0.7.0). You can always view the "Unreleased Notes" in [the latest change log on the 0.7.0 branch](https://github.com/kahmali/meteor-restivus/blob/0.7.0/CHANGELOG.md) (my OCD was broken and didn't catch the missing update to the change log for the iron router replacement, so the only place you'll see that is in a version diff: https://github.com/kahmali/meteor-restivus/compare/v0.6.5...2f83a9b27

I've been a little slow with the updates because after a lot of reconsideration I've decided to move the functionality of restivus into add-on middleware for simple:rest. That way users can get the best of both worlds and be able to construct their DDP and REST API simultaneously. We've already started the process of implementing the middleware pattern and it definitely provides a more modular structure that will make things like #57 almost too easy. I still plan to support Restivus until simple:rest provides all the same functionality. I do think I'll trim some things from the 0.7.0 release, just to get it out the door until I decide if simple:rest will be able to support those things soon enough that it's worth just implementing there. Things like #57 and #50.

I may be able to get the 0.7.0 release out by the end of the week if I trim those things. I already have #64 and #49 pretty much done on local branches and just needing tests and doc updates.

**Comment by kahmali** [comment]
Now that v0.8.0 has been released, the notes can be found in the [change log](https://github.com/kahmali/meteor-restivus/blob/devel/CHANGELOG.md)

**Comment by dandv** [comment]
:+1:
