### ISSUE TITLE
Remove reference to SRP from docs

### ISSUE THREAD

**Issue by dandv** [kahmali/meteor-restivus#88]
[Authenticating](https://github.com/kahmali/meteor-restivus#authenticating) reads:

> In an ideal world, this should only be done with DDP and SRP, but, alas, this is a REST API.

[Meteor dropped SRP support with v0.8.2](https://github.com/meteor/meteor/blob/devel/History.md#meteor-accounts-4). Would SRP still be interesting to use over DDP?

**Comment by kahmali** [comment]
You know, that information is from the original RestStop2 docs. I won't even pretend to know enough about cryptography to have an informed opinion on that. In [this discussion](https://groups.google.com/forum/#!topic/meteor-core/dDD_u6mN4LA) in the Meteor Google group, Emily Stark describes the motivation behind converting from SRP to bcrypt. She clearly knows infinitely more than I do on this topic (and probably many others), so I'll defer to her response. She cites the ability to increase the work factor to keep up with increasing CPU/GPU speed in brute force attacks, and the ability to do so without maintaining their own crypto code as the reasons for the switch. She did say that some devs may still prefer to use SRP and recommended the community maintain an SRP package if they needed it. 

So, I guess for some, SRP may still be interesting to use over DDP (and HTTP too I suppose; apparently it doesn't require SSL/TSL). However, I think it would probably be best if I just removed that bit from the docs, since SRP isn't even being used in Meteor anymore, and according to Emily Stark it has it's own set of pitfalls as well (at least the custom Meteor implementation did), and thus isn't as ideal as the docs may make it out to be.

**Comment by dandv** [comment]
Incidentally, SRP popped up in conversation about the same time I posted this issue: https://github.com/oortcloud/node-ddp-client/issues/39#issuecomment-113580197. Agree that the SRP bit might provide a false sense of security or hope.

**Comment by kahmali** [comment]
Thanks for pointing this out. I'll remove it from the docs.

**Comment by kahmali** [comment]
I updated this on the 0.8.0 branch, which will be released very soon.
