### ISSUE TITLE
OCD suggestion on merging PRs more neatly

### ISSUE THREAD

**Issue by dandv** [kahmali/meteor-restivus#89]
![image](https://cloud.githubusercontent.com/assets/33569/8249137/e96eb264-161b-11e5-8369-2dc20f870253.png)

I [struggled myself](http://stackoverflow.com/questions/27208042/neat-clean-compacted-git-pr-and-merge-commit-into-one-commit) with this one but [managed to get it working](https://github.com/SachaG/meteor-spin/commits/master) :)

![image](https://cloud.githubusercontent.com/assets/33569/8249161/2fff91bc-161c-11e5-8b31-ececee78577e.png)

**Comment by kahmali** [comment]
Great suggestion! (Not that I expect anything less from you) I was actually discussing this issue with a friend recently. I hate that the merge button on GitHub creates an extra merge commit _even when it's a fast-forward merge_! That's just absurd. I'll practice this in a test repo so I don't destroy anything here, but I definitely plan to incorporate this into my workflow. I'll keep this issue open until I pull it off in here for the first time. Thanks for the information!

**Comment by kahmali** [comment]
Hey @dandv! I made an improvement on Meteor's suggested workflow for merging PRs! Wow. I literally have a tear of excitement in my eye right now. This is what a clean commit history does to me. :P I feel like I've achieved the ultimate level of commit history cleanliness. 

All I did was make sure the PR was rebased onto the latest version of the branch I was merging it with, `devel`. Then I checked out the PR branch locally, and _instead of cherry-picking the commit from the PR branch (as Meteor's workflow suggested), I just merged it into `devel`_ with 
```bash
> git checkout pr/97
...test changes...
> git checkout devel
> git merge pr/97
> git push
``` 
That should always be a fast-forward merge, since the branch was rebased on `devel`. 

Check [this history](https://github.com/kahmali/meteor-restivus/commits/devel) out. It comes from PR #97, which you can see is marked as "Merged" on GitHub, as if I had clicked the evil Merge button! What you won't see, however, is any extra merge commit, _or even that unnecessary modification of the commit by the repo owner!_ The large picture on GitHub next to the commit log shows the author of the commit, and the small inset picture is the committer (if they're different -- otherwise only the one pic is shown). So now, the original author and committer can be preserved, without any useless information polluting the commit history. Even better, because the original commit is preserved, GitHub will now be able to detect when that commit is merged upstream, and will automatically mark the PR as "Merged" and close it as soon as the commit is pushed. Yay for git OCD!

The one piece of useful information that is now missing (since there's no more merge commit) is a reference to the PR that a commit comes from. I'll have to add that to my contributing guidelines, so PR numbers are included in commit messages (maybe at the end of the subject line).  Thanks so much for this suggestion! Let me know what you think of my change to the workflow.

**Comment by dandv** [comment]
Such a nice application of this procedure as in #123 [merits mention on StackOverflow](http://stackoverflow.com/posts/29958324/revisions) :)
