### ISSUE TITLE
Restivus from package

### ISSUE THREAD

**Issue by robomatic** [kahmali/meteor-restivus#94]
When nimble:restivus based code is put into a standalone package for import into an app it says 'restivus has no method addCollection' 

package.js
```
Package.onUse(function(api) {
  api.use([
    'meteor-platform',
    'nimble:restivus'
    ]);
  api.add_files([
    'rest-api.js'
    ], 'server');
});
```

**Comment by kahmali** [comment]
This happens to me all the time with meteor packages. You just need to explicitly declare the package version in the `package.js` file. I believe the `addCollection()` method was added in v0.6.1, but I recommend using the latest and greatest. If that doesn't fix it feel free to reopen this. Thanks!

**Comment by robomatic** [comment]
That did the trick. Thank you for the clear answer. I'm wondering why I do not recall this from the docs.

**Comment by kahmali** [comment]
I suppose I could mention this in the Restivus docs. It's something that really belongs in the meteor docs, since it's a meteor-wide issue, and not specific to Restivus. You should get in the habit of checking the version of the package you're using, and making sure you're reading the docs for that version. I've tagged all the releases, so you can easily access the docs for any version. Any half-decent package maintainer will do the same. I've included a screenshot below, in case you're not familiar with where to find those tagged versions:

![screenshot 2015-06-30 14 48 44](https://cloud.githubusercontent.com/assets/935297/8439076/a7eabfca-1f37-11e5-8b45-42b63c0e071e.png)
